[package]
name = "onetimer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.13.3"
log = "0.4.17"
rand = "0.8.5"
simplelog = "0.12.1"
sqlite = "0.30.4"
tiny_http = "0.12.0"
