[database]
kind = "memory" # sqlite, memory, file, mysql, etc
# url = "mysql://onetimer:12345678@localhost:3306/onetimer_db"    # mysql
# url = "./db"                                                    # file
# url = "./db.sqlite"                                             # sqlite, also ":memory:" works

[server]
host = "127.0.0.1"
port = 8080
workers = 32
address = "http://127.0.0.1:8080"

[log]
kind = "console"   # `file` or `console`
file = "./onetimer.log"
level = "info"
