[database]
kind = "sqlite" # sqlite, memory, file, etc
url = "Data Source = ./db.sqlite;"

[server]
host = "127.0.0.1"
port = 8080
workers = 32
address = "http://127.0.0.1:8080"

[log]
kind = "console"   # `file` or `console`
file = "./onetimer.log"
level = "info"
