[database]
type = "memory" # sqlire, memory, etc
path = "./db.sqlite"
# path = ":memory:"

[server]
host = "127.0.0.1"
port = 8080
address = "http://127.0.0.1:8080"

[log]
type = "file"   # `file` or `console`
file = "./onetimer.log"
level = "info"
